import {useEffect,useRef,useState} from 'react';
import type {CSSProperties,ReactNode} from 'react';
import {advance,apply,available,chapterOf,complete,move,newSeason,nextObjective,retryEnding,rollback,season,stageById,tide,visit,waitTide} from './domain/season.ts';
import type {SeasonState,Stage} from './domain/season.ts';
import {asset} from './content/art.ts';
import {Icon} from './GameIcon.tsx';
import ExplorationBar from './ExplorationBar.tsx';
import {getSeasonSlot,writeSeasonSlot} from './platform/season-save.ts';
import type {SeasonSlot} from './platform/season-save.ts';
import './season.css';
import MechanismControls from './MechanismControls.tsx';
import GraphicalMap from './GraphicalMap.tsx';
import useSceneFrame from './useSceneFrame.ts';
import './game-skin.css';
type Modal='inventory'|'notebook'|'map'|'hint'|'settings'|'save'|'puzzle'|'endings'|'restart'|null;
type Prefs={brightness:number;textSize:number;danger:'standard'|'relaxed'|'off';sound:boolean;volume:number};
const defaults:Prefs={brightness:100,textSize:16,danger:'standard',sound:true,volume:35};
function readPrefs():Prefs{try{const p=JSON.parse(localStorage.getItem('pyoryudo-season-preferences')||'{}');return {brightness:Number.isFinite(p.brightness)?Math.max(80,Math.min(120,p.brightness)):100,textSize:[14,16,18].includes(p.textSize)?p.textSize:16,danger:['standard','relaxed','off'].includes(p.danger)?p.danger:'standard',sound:typeof p.sound==='boolean'?p.sound:true,volume:Number.isFinite(p.volume)?Math.max(0,Math.min(100,p.volume)):35};}catch{return defaults;}}
function Panel({title,close,children,notice}:{title:string;close:()=>void;children:ReactNode;notice?:string}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current!;d.showModal();return()=>d.close();},[]);
 return <dialog ref={ref} className="sheet season-sheet" aria-label={title} onCancel={e=>{e.preventDefault();close();}}><header className="sheet-header"><div><small>표류도 · 기억의 해안</small><h2>{title}</h2></div><button className="icon-button" aria-label="닫기" onClick={close}><Icon name="close"/></button></header>{notice&&<p className="season-modal-message" role="alert">{notice}</p>}<div className="sheet-scroll">{children}</div></dialog>;
}
export type SeasonReview={state:SeasonState;screen?:'home'|'game';modal?:Modal;stage?:string;selected?:string;input?:string;values?:string[];notebookTab?:string};
export default function SeasonApp({initial,review,onRestart}:{initial:SeasonState;review?:SeasonReview;onRestart:()=>void}){
 const [s,setState]=useState(review?.state||initial),ref=useRef(s);
 const [showCompletion,setShowCompletion]=useState(true);
 const sceneRef=useRef<HTMLElement>(null),[fullScene,setFullScene]=useState(false);
 const [screen,setScreen]=useState<'home'|'game'>(review?.screen||'home');
 const sceneSize=useSceneFrame(sceneRef,screen==='game',fullScene);
 const [modal,setModal]=useState<Modal>(review?.modal||null);
 const [p,setPuzzle]=useState<Stage|null>(()=>review?.stage?stageById.get(review.stage)||null:null);
 const [input,setInput]=useState<string>(review?.input||''),[values,setValues]=useState<string[]>(review?.values||[]),[selection,setSelection]=useState(review?.selected||''),[hint,setHint]=useState(0),[notice,setNotice]=useState(''),[saveStatus,setSaveStatus]=useState(review?'자동 저장됨':'자동 저장 준비'),[slots,setSlots]=useState<(SeasonSlot|null)[]>([]),[confirm,setConfirm]=useState<string|null>(null);
 const [prefs,setPrefs]=useState<Prefs>(review?defaults:readPrefs),[markers,setMarkers]=useState(false),[targetList,setTargetList]=useState(false),[hidden,setHidden]=useState(document.hidden),[notebookTab,setNotebookTab]=useState(review?.notebookTab||'notes');
 const c=chapterOf(s),dialogue=s.queue[0],active=available(s),progress=c.stages.filter(x=>!x.optional&&s.done.includes(x.id)).length,total=c.stages.filter(x=>!x.optional).length;
 useEffect(()=>{if(!notice||modal)return;const t=setTimeout(()=>setNotice(''),8000);return()=>clearTimeout(t);},[notice,modal]);
 const current=active.find(x=>!x.optional)||active[0];
 useEffect(()=>setShowCompletion(true),[s.chapter]);
 function commit(n:SeasonState){ref.current=n;setState(n);}
 function ping(success=false){if(!prefs.sound||review)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=success?620:390;g.gain.value=prefs.volume/100*.025;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.12);o.stop(a.currentTime+.13);o.onended=()=>{void a.close();};}catch{/* Playback is optional. */}}
 function open(m:Modal){setNotice('');setModal(m);setConfirm(null);ping();if(m==='hint')setHint(0);if(m==='inventory'&&!selection)setSelection(s.inventory[0]||'');}
 function openStage(q:Stage){setTargetList(false);setPuzzle(q);setInput('');setValues([]);setHint(0);setNotice('');setModal('puzzle');ping();}
 function run(inputValue?:string|string[]){if(!p)return;const r=apply(ref.current,p,inputValue);setNotice(r.message);ping(r.ok);if(r.ok){commit(r.state);setModal(null);setPuzzle(null);setInput('');setValues([]);}}
 function navigate(v:number){const n=move(s,v);if(n===s&&v!==s.view){setNotice('안전 경로를 먼저 열어야 들어갈 수 있습니다.');return;}setTargetList(false);commit(n);setNotice('');ping();}
 async function refreshSlots(){try{setSlots(await Promise.all(['auto','slot1','slot2','slot3'].map(getSeasonSlot)));}catch{setNotice('저장 목록을 읽지 못했습니다. 이전 저장 사본으로 복구할 수 있습니다.');}}
 async function manualSave(id:string){try{await writeSeasonSlot(id,ref.current);setNotice('현재 여정을 저장했습니다.');setConfirm(null);await refreshSlots();}catch{setNotice('저장하지 못했습니다. 브라우저 저장 권한과 여유 공간을 확인하세요.');}}
 async function load(id:string){try{const slot=await getSeasonSlot(id);if(!slot){setNotice('이 슬롯에 저장이 없습니다.');return;}commit(slot.state);setModal(null);setScreen('game');setNotice('저장한 여정을 불러왔습니다.');}catch{setNotice('이 저장을 읽지 못했습니다. 이전 사본을 선택하세요.');}}
 useEffect(()=>{if(review)return;const t=setTimeout(()=>{setSaveStatus('저장 중');writeSeasonSlot('auto',s).then(()=>setSaveStatus('자동 저장됨')).catch(()=>setSaveStatus('저장 실패 · 메뉴에서 다시 저장'));},350);return()=>clearTimeout(t);},[s,review]);
 useEffect(()=>{if(review)return;try{localStorage.setItem('pyoryudo-season-preferences',JSON.stringify(prefs));}catch{setNotice('설정은 현재 화면에 적용됩니다.');}},[prefs,review]);
 useEffect(()=>{const change=()=>setHidden(document.hidden);document.addEventListener('visibilitychange',change);return()=>document.removeEventListener('visibilitychange',change);},[]);
 useEffect(()=>{if(review||screen!=='game'||modal||dialogue||hidden||s.ending||complete(s))return;const t=setInterval(()=>{const now=ref.current;let n={...now,playSeconds:now.playSeconds+1};if(now.danger&&prefs.danger!=='off'){const duration=(now.danger.kind==='cave'?180:90)*(prefs.danger==='relaxed'?2:1);if(now.danger.elapsed+1>=duration){n=rollback(n);setNotice('안전한 진입 지점으로 후퇴했습니다. 도구와 기록도 진입 전 상태로 돌아갑니다.');}else n={...n,danger:{...now.danger,elapsed:now.danger.elapsed+1}};}commit(n);},1000);return()=>clearInterval(t);},[screen,modal,dialogue?.id,hidden,review,s.ending,s.chapter,s.done.length,prefs.danger]);
 useEffect(()=>{if(modal==='save')void refreshSlots();},[modal]);
 const duration=(s.danger?.kind==='cave'?180:90)*(prefs.danger==='relaxed'?2:1);
 const evidenceNames:Record<string,string>={E01:'관측 일지 원본',E02:'대피 요청 원본',E03:'방송 보류 서명',E04:'원본 CCTV 백업'};
 const knownNotes=season.chapters.flatMap(x=>x.stages).filter(q=>s.done.includes(q.id)&&q.note);
 const bg=c.id==='CH09'&&s.view===0&&s.flags.generatorRestored?'CH09_A_POWER':c.backgrounds[s.view];
 const missingOriginals=['E01','E02'].filter(id=>!s.evidence.includes(id));
 const close=()=>{setModal(null);setConfirm(null);setNotice('');};
 const nextChapter=()=>{commit(advance(s));setNotice('');};
 return <main className="game-shell season-shell" style={{'--text-size':prefs.textSize+'px'} as CSSProperties}>
 {screen==='home'?<div className="season-home"><div className="season-home-hero"><img src={asset('title_island')} alt="연무도의 낮빛 해안"/><div><small>표류도 · 기억의 해안</small><h1>나의 여정</h1><p>사람과 기록을 함께, 섬 밖으로.</p></div><button className="icon-button" onClick={()=>open('settings')} aria-label="설정"><Icon name="settings"/></button></div><div className="season-home-scroll"><article className="season-resume"><small>{c.number}장 · {c.place}</small><h2>{c.title}</h2><p>{nextObjective(s)}</p><div className="season-progress"><span style={{width:progress/total*100+'%'}}/></div><button className="primary full" onClick={()=>setScreen('game')}>이어서 탐색하기 <Icon name="next"/></button></article><h2 className="section-title">섬의 여정</h2><div className="season-chapters"><article className="season-chapter-card complete"><span>01</span><div><b>폐창고</b><small>첫 번째 문이 열렸다</small></div><Icon name="check"/></article>{season.chapters.map((ch,i)=><button key={ch.id} className={'season-chapter-card '+(i===s.chapter?'current':'')} disabled={i>s.furthest||s.furthest>=7&&i!==s.furthest||!!s.danger} onClick={()=>{commit(visit(s,i));setScreen('game');}}><span>{String(ch.number).padStart(2,'0')}</span><div><b>{ch.place}</b><small>{i>s.furthest?'앞선 여정 완료 후 열립니다':i===s.chapter?'현재 탐색 중':ch.stages.filter(q=>!q.optional).every(q=>s.done.includes(q.id))?'탐색 완료 · 기록 다시 보기':'열린 구역'}</small></div><Icon name={i>s.furthest?'lock':i===s.chapter?'next':'check'}/></button>)}</div><div className="two-actions"><button className="secondary" onClick={()=>open('save')}><Icon name="save"/>저장 기록</button><button className="secondary" onClick={()=>open('endings')}><Icon name="star"/>엔딩 기록</button></div><button className="text-button full" onClick={()=>open('restart')}>1장부터 새 여정</button><p className="season-footnote">{saveStatus} · 이 브라우저에 저장됩니다.</p></div></div>:<>
 <header className="game-header"><button className="icon-button" onClick={()=>setScreen('home')} aria-label="홈 화면"><Icon name="back"/></button><div className="chapter-label"><small>CHAPTER {String(c.number).padStart(2,'0')}</small><strong>{c.title}</strong></div><button className="icon-button" onClick={()=>open('settings')} aria-label="설정"><Icon name="menu"/></button></header>
 <div className="objective"><Icon name="inspect"/><span>{nextObjective(s)}</span><small>{progress}/{total}</small></div>
 <ExplorationBar place={c.place} view={c.views[s.view]} fullScene={fullScene} markers={markers} onFit={()=>setFullScene(!fullScene)} onMarkers={()=>{setMarkers(!markers);ping();}}/>
 <section ref={sceneRef} className="season-scene" data-fit={fullScene?'whole':'fill'} aria-label={c.views[s.view]}><div className={'season-world '+(markers?'show-markers':'')} style={{width:sceneSize.width,height:sceneSize.height,filter:'brightness('+prefs.brightness/100+')'}}><img className="season-background" src={asset(bg)} alt={c.views[s.view]}/>{!dialogue&&(!complete(s)||!showCompletion)&&!s.ending&&active.filter(q=>q.view===s.view).map(q=><button className={'season-target hotspot '+(q.optional?'optional':'')} key={q.id} style={{left:q.rect.x*100+'%',top:q.rect.y*100+'%',width:q.rect.w*100+'%',height:q.rect.h*100+'%'}} onClick={()=>openStage(q)} aria-label={q.title}><span className="target-reticle"><i/></span></button>)}</div>
 {s.danger&&<div className="season-danger"><Icon name="warning" light/><span>{s.danger.kind==='cave'?'수위 · 안전 선반으로':'경보 · 안전 지점으로'} {prefs.danger==='off'?'시간 제한 해제':Math.max(0,duration-s.danger.elapsed)+'초'}</span><button onClick={()=>{commit(rollback(s));setNotice('진입 직전 상태로 안전하게 후퇴했습니다.');}}>후퇴</button></div>}
 {dialogue&&<div className="season-dialogue">{dialogue.portrait&&<img className="season-portrait" src={asset(dialogue.portrait)} alt={dialogue.speaker}/>}<article className="dialogue-card"><div className="speaker-line"><b>{dialogue.speaker}</b>{dialogue.speaker.includes('기록')&&<small>8년 전 보관 기록</small>}</div><button className="dialogue-next" onClick={()=>{commit({...s,queue:s.queue.slice(1),history:[...s.history.filter(d=>d.id!==dialogue.id),dialogue]});ping();}}><p>{dialogue.text}</p><span>다음 <Icon name="next" light/></span></button></article></div>}
 {complete(s)&&showCompletion&&!s.ending&&!dialogue&&<div className="chapter-complete season-complete"><small>CHAPTER {String(c.number).padStart(2,'0')} COMPLETE</small><Icon name="unlock" light/><h2>{c.title}</h2><p>{c.summary}</p>{active.some(q=>q.optional)&&<button className="secondary full" onClick={()=>setShowCompletion(false)}>남은 선택 원본 조사하기</button>}{s.chapter<s.furthest&&<button className="primary full" onClick={()=>commit(visit(s,s.furthest))}>현재 여정으로 복귀</button>}{s.chapter===6&&missingOriginals.length>0?<><p className="season-warning">아직 없는 원본: {missingOriginals.map(id=>evidenceNames[id]).join(', ')}. 폭풍 구간에서는 이전 시설로 돌아갈 수 없습니다.</p><button className="secondary full" onClick={()=>open('map')}>지도에서 원본 회수하기</button><button className="primary full" onClick={()=>setConfirm('storm')}>폭풍 구간으로</button>{confirm==='storm'&&<div className="season-confirm"><p>이전 시설 이동이 제한됩니다. 현재 자료로 계속 진행할 수 있습니다.</p><button className="primary" onClick={()=>{setConfirm(null);nextChapter();}}>현재 자료로 진행</button></div>}</>:<button className="primary full" onClick={nextChapter}>다음 장으로 <Icon name="next"/></button>}</div>}
 {s.ending&&<div className="season-ending"><img src={asset(season.endings[s.ending].asset)} alt={season.endings[s.ending].title}/><div><small>나의 마지막 기록</small><h2>{season.endings[s.ending].title}</h2><p>{season.endings[s.ending].body}</p><button className="primary full" onClick={()=>{commit(retryEnding(s));setNotice('마지막 대면 직전으로 돌아왔습니다.');}}>마지막 선택 다시 하기</button><button className="secondary full" onClick={()=>setScreen('home')}>홈으로</button></div></div>}
 </section>
 <div className="season-route"><button className="icon-button" aria-label="이전 장면" disabled={!!dialogue||s.view===0||!!s.ending} onClick={()=>navigate(s.view-1)}><Icon name="back"/></button><div>{c.views.map((v,i)=><button key={v} disabled={!!dialogue||!!s.ending} className={i===s.view?'selected':''} onClick={()=>navigate(i)} aria-label={v}>{i+1}</button>)}</div><button className="icon-button" aria-label="다음 장면" disabled={!!dialogue||s.view===c.views.length-1||!!s.ending} onClick={()=>navigate(s.view+1)}><Icon name="next"/></button></div>
 <div className="season-context context-actions"><button className="text-button" disabled={!!dialogue||!!s.ending||complete(s)&&showCompletion} aria-expanded={targetList} onClick={()=>{setTargetList(!targetList);ping();}}><Icon name="inspect"/>조사 목록</button><span><Icon name="tide"/>{tide(s).name} · {tide(s).remaining}칸</span><button className="text-button" disabled={!!s.danger||!!dialogue||!!s.ending} onClick={()=>{commit(waitTide(s));setNotice('안전한 장소에서 한 칸 기다렸습니다.');}}>기다리기</button></div>
 {targetList&&!dialogue&&!s.ending&&(!complete(s)||!showCompletion)&&<div className="season-action-strip target-list">{complete(s)&&<button className="secondary" onClick={()=>setShowCompletion(true)}>탐색 완료 · 여정 계속</button>}{active.filter(q=>q.view===s.view).map(q=><button key={q.id} className="secondary" onClick={()=>openStage(q)}>{q.optional?'선택 기록 · ':''}{q.title}</button>)}{!active.some(q=>q.view===s.view)&&<span>다른 장면의 단서를 찾아보세요.</span>}</div>}
 {notice&&<div className="season-notice" role="status" aria-live="polite"><Icon name="document" light/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="안내 닫기"><Icon name="close" light/></button></div>}
 <nav className="bottom-nav season-nav">{(['inventory','notebook','map','hint','save'] as const).map((m,i)=><button key={m} onClick={()=>open(m)}><Icon name={['inventory','notebook','map','hint','save'][i]} light/><strong>{['인벤토리','수첩','지도','힌트','저장'][i]}</strong></button>)}</nav>
 <div className="save-status" role="status">{review?'화면 검토 · 저장하지 않음':saveStatus}</div>
 </>}
 {modal&&<Panel title={{inventory:'인벤토리',notebook:'수첩',map:'섬 지도',hint:'스피커 힌트',settings:'설정',save:'저장 기록',puzzle:p?.title||'확대 조사',endings:'엔딩 기록',restart:'새 여정 시작'}[modal]} close={close} notice={notice}>
 
 {modal==='inventory'&&<><p className="intro-text">도구를 선택하면 설명과 지금 사용할 수 있는 장소를 볼 수 있습니다.</p><div className="inventory-grid">{s.inventory.map(id=><button key={id} className={'item-slot '+(selection===id?'selected':'')} onClick={()=>setSelection(id)}><img src={asset(season.items[id].asset)} alt=""/><span>{season.items[id].name}</span></button>)}</div>{selection&&s.inventory.includes(selection)&&<article className="season-item-detail"><img src={asset(season.items[selection].asset)} alt={season.items[selection].name}/><h3>{season.items[selection].name}</h3><p>{season.items[selection].description}</p>{active.filter(q=>q.view===s.view&&q.requiresItems?.includes(selection)).map(q=><button className="primary full" key={q.id} onClick={()=>openStage(q)}>{q.kind==='combine'?'조합하기':'사용하기'} · {q.title}</button>)}</article>}<p className="season-footnote">성공한 사용에만 표시된 소모품이 사라집니다. 드라이버와 UV 램프는 계속 보관합니다.</p></>}
 {modal==='notebook'&&<><div className="season-tabs">{[['notes','조사 기록'],['evidence','원본 자료'],['timeline','시간 정리'],['dialogue','대화']].map(([id,label])=><button className={notebookTab===id?'selected':''} key={id} onClick={()=>setNotebookTab(id)}>{label}</button>)}</div>{notebookTab==='notes'&&<>{knownNotes.length===0?<p>확인한 단서는 여기 기록됩니다.</p>:knownNotes.slice().reverse().map(q=><article className="season-note" key={q.id}><small>{q.id.slice(2,4)}장 · {q.evidence||'조사 메모'}</small><h3>{q.note!.title}</h3><p>{q.note!.body}</p></article>)}</>}{notebookTab==='evidence'&&<>{['E01','E02','E03','E04'].map(id=>{const q=knownNotes.find(x=>x.evidence===id);return <article className="season-note" key={id}><small>{id} · {q?'확보함':'아직 확보하지 못함'}</small><h3>{evidenceNames[id]}</h3><p>{q?.note?.body||'원본을 직접 확인하고 보관하면 내용이 기록됩니다.'}</p></article>;})}</>}{notebookTab==='dialogue'&&<>{s.history.length?s.history.slice().reverse().map(d=><article className="season-note" key={d.id}><h3>{d.speaker}</h3><p>{d.text}</p></article>):<p>읽은 대화가 이곳에 남습니다.</p>}</>}{notebookTab==='timeline'&&<>{knownNotes.filter(q=>/18:40|19:10|19:35|20:05|9월 1[567]/.test(q.note!.body)).map(q=><article className="season-note" key={q.id}><h3>{q.note!.title}</h3><p>{q.note!.body}</p></article>)}</>}</>}
 {modal==='map'&&<><GraphicalMap kind="island" current={c.id} places={[{id:'CH01',name:'폐창고',number:1,unlocked:false,known:true,reason:'탐색 완료'},...season.chapters.map((ch,i)=>({id:ch.id,name:ch.place,number:ch.number,known:i<=s.furthest,unlocked:!s.danger&&i<=s.furthest&&(s.furthest<7||i===s.furthest),reason:s.danger?'위험 구간':s.furthest>=7&&i!==s.furthest?'폭풍으로 통행 제한':'잠김'}))]} onSelect={id=>{const i=season.chapters.findIndex(ch=>ch.id===id);if(i<0)return;commit(visit(s,i));close();setScreen('game');}}/><p className="intro-text">{s.danger?'위험 구간에서는 안전 선반 또는 은신 지점에 도착해야 이동할 수 있습니다.':s.furthest>=7?'폭풍으로 이전 시설 이동이 제한됐습니다. 기록은 수첩에서 읽을 수 있습니다.':'열린 장소의 표식을 누르면 이동합니다. 폭풍 전에는 원본을 다시 회수할 수 있습니다.'}</p>{s.chapter<s.furthest&&<button className="primary full" onClick={()=>{commit(visit(s,s.furthest));close();}}>현재 여정으로 복귀</button>}</>}
 {modal==='hint'&&<><img className="season-hint-icon" src={asset('tide_watch')} alt=""/><h3>{current?.title||'현재 구역 탐색 완료'}</h3><p className="intro-text">스피커 힌트는 단계별로 더 구체적인 내용을 들려줍니다.</p>{current&&<><p className="season-clue">{current.hints[Math.min(hint,2)]}</p><button className="primary full" disabled={hint>=2} onClick={()=>setHint(hint+1)}>{hint>=2?'마지막 힌트입니다':'다음 힌트 · '+(hint+2)+'단계'}</button></>}</>}
 {modal==='settings'&&<><div className="season-setting"><label htmlFor="brightness">화면 밝기 <b>{prefs.brightness}%</b></label><input id="brightness" type="range" min="80" max="120" value={prefs.brightness} onChange={e=>setPrefs({...prefs,brightness:+e.target.value})}/></div><div className="season-setting"><label>대화 글자 크기</label><div className="season-options">{[14,16,18].map(n=><button key={n} className={prefs.textSize===n?'selected':''} onClick={()=>setPrefs({...prefs,textSize:n})}>{n===14?'작게':n===16?'기본':'크게'}</button>)}</div></div><div className="season-setting"><label htmlFor="danger">위험 구간 시간</label><select id="danger" value={prefs.danger} onChange={e=>setPrefs({...prefs,danger:e.target.value as Prefs['danger']})}><option value="standard">기본 · 동굴 180초 / 경보 90초</option><option value="relaxed">여유 · 두 배</option><option value="off">시간 제한 해제</option></select><p>대화·퍼즐·메뉴·화면 비활성 중 정지합니다. 후퇴하면 진입 전 도구와 기록도 복원됩니다.</p></div><div className="season-setting"><label><input type="checkbox" checked={prefs.sound} onChange={e=>setPrefs({...prefs,sound:e.target.checked})}/> 조작 효과음</label><input aria-label="효과음 음량" type="range" min="0" max="100" value={prefs.volume} onChange={e=>setPrefs({...prefs,volume:+e.target.value})}/></div><p className="season-clue" style={{fontSize:prefs.textSize}}>밝은 바닷빛 아래에서도 사라진 기록은 남아 있다.</p><button className="secondary full" onClick={()=>setPrefs(defaults)}>기본 설정으로</button><button className="secondary full" onClick={()=>open('save')}>저장과 불러오기</button><p className="season-footnote">Pretendard Variable · 오프라인 로컬 폰트<br/>현재 효과음은 간단한 조작음입니다. 음악과 성우 음성은 별도 제작 범위입니다.</p></>}
 {modal==='save'&&<>{['auto','slot1','slot2','slot3'].map((id,i)=>{const slot=slots.find(x=>x?.id===id);return <article className="season-note" key={id}><h3>{i?'수동 저장 '+i:'자동 저장'}</h3><p>{slot?season.chapters[slot.state.chapter].number+'장 · '+season.chapters[slot.state.chapter].place:'비어 있는 슬롯'}</p><small>{slot?new Date(slot.savedAt).toLocaleString('ko-KR'):'현재 여정을 보관하세요.'}</small><div className="two-actions">{i>0&&<button className="secondary" onClick={()=>slot?setConfirm(id):void manualSave(id)}>저장</button>}<button className="secondary" onClick={()=>void load(id)}>불러오기</button><button className="text-button" onClick={()=>void load(id+'.backup')}>이전 사본</button></div>{confirm===id&&<div className="season-confirm"><p>이 슬롯을 현재 여정으로 바꿉니다. 이전 저장은 사본으로 남습니다.</p><button className="primary" onClick={()=>void manualSave(id)}>저장하기</button></div>}</article>;})}<p className="season-footnote">1장 저장과 시즌 저장은 별도로 보관됩니다.</p></>}
 {modal==='endings'&&<>{s.seenEndings.length===0?<p className="intro-text">마지막 선택을 마치면 직접 본 엔딩이 여기 남습니다.</p>:s.seenEndings.map(id=><article className="season-note" key={id}><img className="season-ending-thumb" src={asset(season.endings[id].asset)} alt=""/><h3>{season.endings[id].title}</h3><p>{season.endings[id].body}</p></article>)}</>}
 {modal==='restart'&&<><p className="intro-text">1장부터 새 여정을 시작합니다. 시즌의 자동 저장과 수동 슬롯을 비우고 기존 1장 저장을 새 진행으로 바꿉니다.</p><button className="primary full" onClick={onRestart}>새 여정 시작</button><button className="secondary full" onClick={close}>현재 여정 계속</button></>}
 {modal==='puzzle'&&p&&<><div className="season-puzzle-meta"><span>{c.views[p.view]}</span><span>{p.optional?'선택 원본':'단계 '+p.number}</span></div>{['use','combine','sequence','code'].includes(p.kind)&&<div className="season-puzzle-image"><img src={asset(c.closeup)} alt={p.title}/><span>{p.kind==='use'?'도구 연결':p.kind==='code'?'번호 확인':'장치 조작'}</span></div>}<p className="season-puzzle-description">{p.description}</p>{p.kind==='controls'&&<MechanismControls stage={p} image={c.closeup} values={values} onChange={v=>{setValues(v);ping();}}/>}{p.clue&&<p className="season-clue">{p.clue}</p>}{p.clueRefs.length>0&&<details className="season-clues"><summary>확인한 현장 단서 ({p.clueRefs.length})</summary>{p.clueRefs.map(id=>{const q=stageById.get(id);return s.done.includes(id)&&q?<article className="season-note" key={id}><h3>{q.title}</h3><p>{q.note?.body||q.description}</p></article>:null;})}</details>}
 {p.kind==='code'&&<><input className="season-code" aria-label="번호 입력" inputMode="numeric" autoComplete="off" value={input} maxLength={6} onChange={e=>setInput(e.target.value.replace(/\D/g,''))} placeholder="번호를 입력하세요"/><div className="season-keypad">{['1','2','3','4','5','6','7','8','9','지우기','0','←'].map(n=><button key={n} onClick={()=>setInput(n==='지우기'?'':n==='←'?input.slice(0,-1):(input+n).slice(0,6))}>{n}</button>)}</div></>}
 {p.kind==='sequence'&&<><div className="season-sequence"><b>선택한 순서</b><p>{values.length?values.join(' → '):'아래 항목을 순서대로 선택하세요.'}</p></div><div className="season-options">{p.options?.map(o=><button key={o.value} disabled={values.includes(o.value)} onClick={()=>setValues([...values,o.value])}>{o.label}</button>)}</div><button className="text-button full" onClick={()=>setValues([])}>순서 다시 고르기</button></>}
 {(p.kind==='use'||p.kind==='combine')&&<><h3 className="section-title">{p.kind==='combine'?'두 도구를 선택하세요':'사용할 도구를 선택하세요'}</h3><div className="inventory-grid compact">{s.inventory.map(id=><button key={id} className={'item-slot '+((p.kind==='use'?input===id:values.includes(id))?'selected':'')} onClick={()=>{if(p.kind==='use')setInput(id);else setValues(values.includes(id)?values.filter(x=>x!==id):values.length<2?[...values,id]:[id]);}}><img src={asset(season.items[id].asset)} alt=""/><span>{season.items[id].name}</span></button>)}</div></>}
 {p.kind==='choice'?<div className="season-choices">{p.options?.map(o=><button className="secondary full" key={o.value} onClick={()=>run(o.value)}>{o.label}</button>)}</div>:<button className="primary full season-puzzle-confirm" disabled={p.kind==='controls'&&values.filter(Boolean).length!==(p.controls?.length||0)||p.kind==='code'&&!input||p.kind==='use'&&!input||p.kind==='combine'&&values.length!==2||p.kind==='sequence'&&values.length===0} onClick={()=>run(p.kind==='controls'||p.kind==='sequence'?values:p.kind==='combine'?[...values].sort((a,b)=>(p.solution as string[]).indexOf(a)-(p.solution as string[]).indexOf(b)):p.kind==='code'||p.kind==='use'?input:undefined)}>{p.kind==='take'?'챙기기':p.kind==='inspect'?'확인하고 기록하기':p.kind==='exit'?'길을 따라 이동하기':p.kind==='tide'?'안전 구간 진입':'조작 확인'}</button>}
 <button className="text-button full" onClick={()=>setHint(Math.min(3,hint+1))}>단계별 힌트 {hint?'· '+hint+'/3':''}</button>{hint>0&&<p className="season-clue">{p.hints[hint-1]}</p>}</>}
 </Panel>}
 </main>;
}
