import test from 'node:test';
import assert from 'node:assert/strict';
import {advance,apply,available,complete,move,newSeason,retryEnding,rollback,season,tide,visit,waitTide,restore} from '../../src/domain/season.ts';
import type {SeasonState,Stage} from '../../src/domain/season.ts';
function act(s:SeasonState,p:Stage,input?:string|string[]){s={...s,queue:[]};s=move(s,p.view);if(p.kind==='tide')while(!tide(s).entry)s=waitTide(s);const r=apply(s,p,input??p.solution??(p.kind==='choice'?p.options?.[0].value:undefined));assert.equal(r.ok,true,p.id+': '+r.message);return {...r.state,queue:[]};}
function journey(optional=true,admit=true,force=false,stop=8){let s={...newSeason(),queue:[]};for(let ch=0;ch<=stop;ch++){for(const p of season.chapters[ch].stages){if(!optional&&p.optional)continue;s=act(s,p,p.id==='CH08_P16'?(admit?'admit':'deny'):p.id==='CH10_P19'?(force?'force':'peace'):undefined);if(s.ending)break;}if(ch<stop)s={...advance(s),queue:[]};}return s;}
test('nine chapter journey preserves four originals, rescue and distinct ending conditions',()=>{const full=journey();assert.equal(full.ending,'T');assert.equal(full.done.length,180);assert.equal(full.inventory.includes('backup_drive'),true);assert.equal(full.flags.allRescued,true);assert.deepEqual(restore(full),full);assert.equal(journey(false).ending,'N');assert.equal(journey(true,false).ending,'N');const failed=journey(true,true,true);assert.equal(failed.ending,'B');const retry=retryEnding(failed);assert.equal(retry.ending,null);assert(!retry.done.includes('CH10_P19'));assert(retry.done.includes('CH10_P18'));});
test('wrong physical setting and repeated item use keep an atomic inventory',()=>{let s={...newSeason(),queue:[]};for(const p of season.chapters[0].stages.slice(0,8))s=act(s,p);const p=season.chapters[0].stages[8];s=move(s,p.view);const bad=apply(s,p,'screwdriver');assert.equal(bad.ok,false);assert.deepEqual(bad.state,s);const good=apply(s,p,'pump_contact');assert.equal(good.ok,true);assert(!good.state.inventory.includes('pump_contact'));assert.equal(apply(good.state,p,'pump_contact').ok,false);assert.equal(good.state.done.filter(id=>id===p.id).length,1);});
test('cave retreat restores consumed reflector and safe entrance, while time spent remains',()=>{let s={...newSeason(),queue:[]};for(const p of season.chapters[0].stages)s=act(s,p);s={...advance(s),queue:[]};for(const p of season.chapters[1].stages.slice(0,7))s=act(s,p);assert(s.danger);assert(!s.inventory.includes('reflector_disk'));const saved=restore(s);const retreat=rollback({...saved,playSeconds:123});assert.equal(retreat.view,0);assert(retreat.inventory.includes('reflector_disk'));assert(!retreat.done.includes('CH03_P04'));assert.equal(retreat.playSeconds,123);assert.equal(retreat.danger,null);});
test('optional originals can be recovered by revisiting before storm, but storm blocks travel',()=>{let s=journey(false,true,false,6);assert.equal(s.furthest,6);s=visit(s,0);const p=season.chapters[0].stages.find(p=>p.evidence==='E01')!;assert(available(s).includes(p));s=act(s,p);assert(s.evidence.includes('E01'));s=visit(s,2);s=act(s,season.chapters[2].stages.find(p=>p.evidence==='E02')!);s=visit(s,6);assert(complete(s));s=advance(s);assert.equal(s.furthest,7);assert.equal(visit(s,0),s);});
